on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target deployment environment. Acceptable values are 'dev', 'qa', or 'prod'

jobs:
  lint: 
    name: Lint
    if: github.event_name == 'pull_request'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: PyLint 
      run: |
        pip install -r requirements.txt
        pip install pylint
        pylint --recursive=y .

  scan:
    name: Scan
    if: github.event_name == 'pull_request'
    runs-on: 'ubuntu-latest'
    needs: lint
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


  image-build-push: 
    if: github.event_name == 'push'
    name: "Image Build & Push"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Authentication
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'     # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Authentication
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ vars.region }}-docker.pkg.dev'
      - name: Test Debug
        id: debug
        run: |-
          ls -al

      - name: Build and Tag
        id: build-image
        uses: docker/build-push-action@v3
        with:
          push: true 
          tags: |
            ${{ vars.region }}-docker.pkg.dev/${{ vars.artifact_registry_project }}/${{ vars.artifact_registry_repo }}/${{ vars.service_name }}:${{ github.sha }}
            ${{ vars.region }}-docker.pkg.dev/${{ vars.artifact_registry_project }}/${{ vars.artifact_registry_repo }}/${{ vars.service_name }}:latest
      
      - name: Docker Push
        shell: bash
        run: |-
          docker push "${{ vars.region }}-docker.pkg.dev/${{ vars.artifact_registry_project }}/${{ vars.artifact_registry_repo }}/${{ vars.service_name }}:${{ github.sha }}"
          docker push "${{ vars.region }}-docker.pkg.dev/${{ vars.artifact_registry_project }}/${{ vars.artifact_registry_repo }}/${{ vars.service_name }}:latest"

  deploy: 
    if: github.event_name == 'push' 
    name: "Cloud Run Deployment"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [image-build-push]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Authentication
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'     # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Create Service ${{ inputs.environment }} Declaration   
        run: |-
          export CONTAINER_IMAGE="${{ vars.region }}-docker.pkg.dev/${{ vars.artifact_registry_project }}/${{ vars.artifact_registry_repo }}/${{ vars.service_name }}:${{ github.sha }}"
          export SERVICE_NAME="${{ vars.service_name }}"
          export PROJECT_ID="${{ vars.google_cloud_project }}"
          export REVISION_TAG="${{ github.sha }}"
          export CLOUD_RUN_SA="${{ vars.cloud_run_sa }}"
          export REGION="${{ vars.region }}"
          export ENVIRONMENT="${{ inputs.environment }}"
          envsubst < ./service-yaml/container-${{ inputs.environment }}.yaml > container-${{ inputs.environment }}.yaml

      - name: Deploy to ${{ inputs.environment }} Cloud Run
        id: deploy-dev-qa
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ vars.google_cloud_project }}
          service: ${{ vars.service_name }}
          region: ${{ vars.region }}
          metadata: container-${{ inputs.environment }}.yaml